/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package tr.com.argela.obs.client.api;

import tr.com.argela.obs.client.model.Grade;
import tr.com.argela.obs.client.model.ResponseEntity;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GradeControllerApi
 */
@Ignore
public class GradeControllerApiTest {

    private final GradeControllerApi api = new GradeControllerApi();

    
    /**
     * deleteById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByIdUsingDELETETest() {
        Long id = null;
        String token = null;
        api.deleteByIdUsingDELETE(id, token);

        // TODO: test validations
    }
    
    /**
     * findById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByIdUsingGETTest() {
        Long id = null;
        String token = null;
        ResponseEntity response = api.findByIdUsingGET(id, token);

        // TODO: test validations
    }
    
    /**
     * getAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUsingGETTest() {
        String token = null;
        List<Grade> response = api.getAllUsingGET(token);

        // TODO: test validations
    }
    
    /**
     * getGradeLectureById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGradeLectureByIdUsingGETTest() {
        Long lectureId = null;
        String token = null;
        List<Grade> response = api.getGradeLectureByIdUsingGET(lectureId, token);

        // TODO: test validations
    }
    
    /**
     * getGradeStudentById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGradeStudentByIdUsingGETTest() {
        Long studentId = null;
        String token = null;
        List<Grade> response = api.getGradeStudentByIdUsingGET(studentId, token);

        // TODO: test validations
    }
    
    /**
     * getGradesByLectureStudentId
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGradesByLectureStudentIdUsingGETTest() {
        Long lectureId = null;
        Long studentId = null;
        String token = null;
        List<Grade> response = api.getGradesByLectureStudentIdUsingGET(lectureId, studentId, token);

        // TODO: test validations
    }
    
    /**
     * save
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveUsingPOSTTest() {
        Grade grade = null;
        Grade response = api.saveUsingPOST(grade);

        // TODO: test validations
    }
    
    /**
     * value
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void valueUsingPUTTest() {
        Long lectureId = null;
        Long studentId = null;
        String token = null;
        Integer value = null;
        Grade response = api.valueUsingPUT(lectureId, studentId, token, value);

        // TODO: test validations
    }
    
}
