/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package tr.com.argela.obs.client.api;

import tr.com.argela.obs.client.model.Lecture;
import tr.com.argela.obs.client.model.ResponseEntity;
import tr.com.argela.obs.client.model.Teacher;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TeacherControllerApi
 */
@Ignore
public class TeacherControllerApiTest {

    private final TeacherControllerApi api = new TeacherControllerApi();

    
    /**
     * deleteById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByIdUsingDELETE3Test() {
        Long id = null;
        String token = null;
        ResponseEntity response = api.deleteByIdUsingDELETE3(id, token);

        // TODO: test validations
    }
    
    /**
     * findById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByIdUsingGET3Test() {
        Long id = null;
        String token = null;
        ResponseEntity response = api.findByIdUsingGET3(id, token);

        // TODO: test validations
    }
    
    /**
     * getAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUsingGET3Test() {
        String token = null;
        List<Teacher> response = api.getAllUsingGET3(token);

        // TODO: test validations
    }
    
    /**
     * getLecturesByTeacherId
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLecturesByTeacherIdUsingGETTest() {
        Integer teacherId = null;
        String token = null;
        List<Lecture> response = api.getLecturesByTeacherIdUsingGET(teacherId, token);

        // TODO: test validations
    }
    
    /**
     * save
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveUsingPOST3Test() {
        Teacher teacher = null;
        Teacher response = api.saveUsingPOST3(teacher);

        // TODO: test validations
    }
    
}
