/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package tr.com.argela.obs.client.api;

import tr.com.argela.obs.client.model.LoggedUser;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserControllerApi
 */
@Ignore
public class UserControllerApiTest {

    private final UserControllerApi api = new UserControllerApi();

    
    /**
     * getLoggedUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLoggedUserUsingGETTest() {
        String token = null;
        LoggedUser response = api.getLoggedUserUsingGET(token);

        // TODO: test validations
    }
    
    /**
     * login
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginUsingPUTTest() {
        String password = null;
        String user = null;
        String response = api.loginUsingPUT(password, user);

        // TODO: test validations
    }
    
    /**
     * logout
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logoutUsingDELETETest() {
        String token = null;
        api.logoutUsingDELETE(token);

        // TODO: test validations
    }
    
}
